from . import estate_property
from . import crm_inherit_crm_lead
from . import product_inherit_product_template
from . import inherit_res_partner
from . import sector_info
from . import market_category
from . import customer_type
from . import crm_account_type
from . import crm_purchase_time_frame
from . import crm_payment_terms
from . import product_manufacturer
from . import crm_status
from . import sale_order_line_inherit
